name: Deploy ETL Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy Cloud Functions
      run: |
        gcloud functions deploy weather_extract \
          --runtime python39 \
          --trigger-topic weather-extract-topic \
          --region us-central1 \
          --project $PROJECT_ID

        gcloud functions deploy weather_transform \
          --runtime python39 \
          --trigger-topic weather-transform-topic \
          --region us-central1 \
          --project $PROJECT_ID

    - name: Terraform Init and Apply
      working-directory: terraform
      run: |
        terraform init
        terraform apply -auto-approve -var="project_id=$PROJECT_ID" -var="notification_email=francodomino2021@gmail.com"
